### ISSUE TITLE
Some Quality-of-Life suggestions

### ISSUE THREAD

**Issue by C-Fu** [Zhoros/XenStream#2]
I absolutely love this!

Some suggestions that you can consider if you want:

1. A lot of us or your users are probably Plex/Jellyfin/etc users, and we are used to the folder structure like below:
Main folder: Movies
Movie name (year)
|- movie name.mp4/.mkv
|- movie name.srt
Movie 2 (year)
|- movie 2.mp4
|- movie 2.srt

My suggestion would be to be able to do something like this in docker-compose.yml, and xenstream would be able to pick up the movie folders and play the first/only file there... or maybe even play everything in that folder (with the added next/back button)
```
services:
  xenstream:
    container_name: xenstream
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
    volumes:
      - "/mnt/Movies:/app/videos"
```

2. An env var to enable transcoding, something like
```
services:
  xenstream:
    container_name: xenstream
    restart: unless-stopped
    build: .
    environment:
      - ENABLE_TRANSCODING=true
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "80:80"
    volumes:
      - "/mnt/14tera/Movies:/app/videos"
```

3. A way to be able to embed the video player somewhere, something like
```
services:
  xenstream:
    container_name: xenstream
    restart: unless-stopped
    build: .
    environment:
      - "EMBED_VIDEO_ALLOWED_URL=https://mylinkstack.com"
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "80:80"
    volumes:
      - "/mnt/14tera/Movies:/app/videos"
```

4. Make the seek font a lot bigger

![Image](https://github.com/user-attachments/assets/a8d59d8a-39f7-4abd-b475-d5ffd24244e9)

5. Caption position slider is next to zoom slider, not below

Keep up the good work dude!
